### PR TITLE
Use @most/eslint-config-most

### PR DESCRIPTION
**Pull request by briancavalier**
Here we go.  The first package to consume [`eslint-config-most`](https://github.com/mostjs/eslint-config-most)

### CODE REVIEW

**Comment by TylorS** [comment]
For node 4 you'll have to explicitly depend on eslint-config-standard

**Comment by briancavalier** [comment]
Ah, darn.  That's a bummer.  Thanks, I'll update it.

**Comment by briancavalier** [comment]
Hmmm, I wonder then if it also makes sense for eslint-config-most to list [these three packages](https://github.com/mostjs/eslint-config-most/blob/master/package.json#L16-L20) as _both_ dependencies _and_ peerDependencies??

**Comment by TylorS** [comment]
That could work

**Comment by briancavalier** [comment]
Ok, [eslint-config-standard does something similar](https://github.com/feross/eslint-config-standard/blob/master/package.json#L48-L52), though it _only_ lists them as peers.  I think I'm sold on doing both for now so that node 5 users get the nice auto-install benefit.

**Comment by briancavalier** [comment]
Whatdya think? Ok to merge?

**Comment by TylorS** [comment]
:+1:

**Pull request merged**
